//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsMedia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsMedia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une sélection.
        /// </summary>
        public static string AddWindowTitle {
            get {
                return ResourceManager.GetString("AddWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer la bibliothèque.
        /// </summary>
        public static string BiblioWindowTitle {
            get {
                return ResourceManager.GetString("BiblioWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BluePlaylistIcon {
            get {
                object obj = ResourceManager.GetObject("BluePlaylistIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éléments.
        /// </summary>
        public static string BoxElements {
            get {
                return ResourceManager.GetString("BoxElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter....
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string ButtonAlbum {
            get {
                return ResourceManager.GetString("ButtonAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artistes.
        /// </summary>
        public static string ButtonArtist {
            get {
                return ResourceManager.GetString("ButtonArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string ButtonDel {
            get {
                return ResourceManager.GetString("ButtonDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string ButtonGenre {
            get {
                return ResourceManager.GetString("ButtonGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string ButtonPlaylistAdd {
            get {
                return ResourceManager.GetString("ButtonPlaylistAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string ButtonPlaylistDel {
            get {
                return ResourceManager.GetString("ButtonPlaylistDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renommer.
        /// </summary>
        public static string ButtonPlaylistRename {
            get {
                return ResourceManager.GetString("ButtonPlaylistRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DefaultMusicImage {
            get {
                object obj = ResourceManager.GetObject("DefaultMusicImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DefaultPicImage {
            get {
                object obj = ResourceManager.GetObject("DefaultPicImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DefaultVideoImage {
            get {
                object obj = ResourceManager.GetObject("DefaultVideoImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer une sélection.
        /// </summary>
        public static string DeleteWindowTitle {
            get {
                return ResourceManager.GetString("DeleteWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DisableRepeat {
            get {
                object obj = ResourceManager.GetObject("DisableRepeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DisableShuffle {
            get {
                object obj = ResourceManager.GetObject("DisableShuffle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EnableRepeat {
            get {
                object obj = ResourceManager.GetObject("EnableRepeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EnableShuffle {
            get {
                object obj = ResourceManager.GetObject("EnableShuffle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GreenPlaylistIcon {
            get {
                object obj = ResourceManager.GetObject("GreenPlaylistIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la sélection :.
        /// </summary>
        public static string LabelAdd {
            get {
                return ResourceManager.GetString("LabelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement des bibliothèques.
        /// </summary>
        public static string LabelBiblio {
            get {
                return ResourceManager.GetString("LabelBiblio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etes-vous sûr de vouloir effacer la sélection.
        /// </summary>
        public static string LabelDel {
            get {
                return ResourceManager.GetString("LabelDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de la sélection ne peut pas être vide !.
        /// </summary>
        public static string LabelEmpty {
            get {
                return ResourceManager.GetString("LabelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La liste de lecture est vide !.
        /// </summary>
        public static string LabelPlaylist {
            get {
                return ResourceManager.GetString("LabelPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la sélection :.
        /// </summary>
        public static string LabelRename {
            get {
                return ResourceManager.GetString("LabelRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom saisi est déjà utilisé par une autre sélection !.
        /// </summary>
        public static string LabelUsed {
            get {
                return ResourceManager.GetString("LabelUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Loupe {
            get {
                object obj = ResourceManager.GetObject("Loupe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGES.
        /// </summary>
        public static string MenuImage {
            get {
                return ResourceManager.GetString("MenuImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langues.
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothèques....
        /// </summary>
        public static string MenuLibrary {
            get {
                return ResourceManager.GetString("MenuLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUSIQUES.
        /// </summary>
        public static string MenuMusic {
            get {
                return ResourceManager.GetString("MenuMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir....
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafraîchir.
        /// </summary>
        public static string MenuRefresh {
            get {
                return ResourceManager.GetString("MenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECTIONS.
        /// </summary>
        public static string MenuSelection {
            get {
                return ResourceManager.GetString("MenuSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEOS.
        /// </summary>
        public static string MenuVideo {
            get {
                return ResourceManager.GetString("MenuVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mute {
            get {
                object obj = ResourceManager.GetObject("Mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Next {
            get {
                object obj = ResourceManager.GetObject("Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PinkPlaylistIcon {
            get {
                object obj = ResourceManager.GetObject("PinkPlaylistIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PurplePlaylistIcon {
            get {
                object obj = ResourceManager.GetObject("PurplePlaylistIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RedPlaylistIcon {
            get {
                object obj = ResourceManager.GetObject("RedPlaylistIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renommer une sélection.
        /// </summary>
        public static string RenameWindowTitle {
            get {
                return ResourceManager.GetString("RenameWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Volume1 {
            get {
                object obj = ResourceManager.GetObject("Volume1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Volume2 {
            get {
                object obj = ResourceManager.GetObject("Volume2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Volume3 {
            get {
                object obj = ResourceManager.GetObject("Volume3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
